export enum WeaponType {
  Sword = "Sword",
  Dagger = "Dagger",
  Axe = "Axe",
  Hammer = "Hammer",
  Mace = "Mace",
  Measure = "Measure",
  Greatsword = "Greatsword",
  Katana = "Katana",
  NinjaSword = "NinjaSword",
  Spear = "Spear",
  Pole = "Pole",
  Rod = "Rod",
  Stave = "Stave",
  Bow = "Bow",
  Arrow = "Arrow",
  Crossbow = "Crossbow",
  Bolt = "Bolt",
  Gun = "Gun",
  Shot = "Shot",
  HandBomb = "HandBomb",
  Bomb = "Bomb",
  Magick = "Magick",
  Heal = "Heal",
  Unarmed = "Unarmed"
}